name: fc_teams_drawer
description: "An app for all FIFA players or any other soccer game."
publish_to: 'none'

version: 2.2.0+58

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  mobile_device_identifier: ^0.0.3
  flutter_launcher_icons: ^0.14.3
  firebase_performance: ^0.10.1+4
  flutter_secure_storage: ^9.2.4
  firebase_crashlytics: ^4.3.4
  firebase_app_check: ^0.3.2+4
  firebase_analytics: ^11.4.4
  isar_flutter_libs: ^3.1.0+1
  shimmer_animation: ^2.2.2
  firebase_database: ^11.3.4
  device_info_plus: ^11.3.0
  new_version_plus: ^0.1.0
  cloud_firestore: ^5.6.5
  firebase_core: ^3.12.1
  flutter_i18n: ^0.36.2
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  flutter_mobx: ^2.3.0
  injectable: ^2.5.0
  equatable: ^2.0.7
  provider: ^6.1.4
  isar: ^3.1.0+1
  dartz: ^0.10.1
  get_it: ^8.0.3
  intl: ^0.19.0
  mobx: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.4.4
  injectable_generator: ^2.4.2
  isar_generator: ^3.1.0+1
  flutter_lints: ^5.0.0
  mobx_codegen: ^2.6.2
  build_runner: ^2.4.13

# configuracao do launch icon
flutter_launcher_icons:
  image_path: "assets/img/logo.jpg"
  android: true
  ios: true
  min_sdk_android: 19
  remove_alpha_ios: true
  background_color_ios: "#334790"

  # configuracao da splash
flutter_native_splash:
  color: "#334790"
  color_dark: "#334790"
  image: assets/img/logo.jpg
  image_dark: assets/img/logo.jpg
  android: true
  ios: true
  fullscreen: true

  android_12:
    image: assets/img/logo.jpg
    icon_background_color: "#334790"
    image_dark: assets/img/logo.jpg
    icon_background_color_dark: "#334790"

  web: false

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - assets/fonts/
    - assets/img/teams/
    - assets/languages/

  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
