name: fc_teams_drawer
description: "An app for all FIFA players or any other soccer game."
publish_to: 'none'

version: 2.0.0+19

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  firebase_performance: ^0.9.4+7
  flutter_secure_storage: ^9.2.2
  firebase_crashlytics: ^3.5.7
  firebase_app_check: ^0.2.2+7
  firebase_analytics: ^10.10.7
  shimmer_animation: ^2.1.0+1
  firebase_database: ^10.5.7
  connectivity_plus: ^6.0.3
  device_info_plus: ^10.1.0
  new_version_plus: ^0.0.11
  cloud_firestore: ^4.17.5
  cupertino_icons: ^1.0.8
  flutter_mobx: ^2.2.1+1
  firebase_core: ^2.32.0
  flutter_i18n: ^0.35.1
  path_provider: 2.1.3
  injectable: ^2.4.2
  equatable: ^2.0.5
  provider: ^6.1.2
  sqflite: ^2.4.1
  dartz: ^0.10.1
  get_it: ^7.7.0
  mobx: ^2.3.3+2
  floor: ^1.5.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^2.4.0
  injectable_generator: ^2.4.2
  floor_generator: ^1.5.0
  flutter_lints: ^4.0.0
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.9

# configuracao do launch icon
flutter_launcher_icons:
  image_path: "assets/img/logo.jpg"
  android: true
  ios: true
  min_sdk_android: 19
  remove_alpha_ios: true
  background_color_ios: "#334790"

  # configuracao da splash
flutter_native_splash:
  color: "#334790"
  color_dark: "#334790"
  image: assets/img/logo.jpg
  image_dark: assets/img/logo.jpg
  android: true
  ios: true
  fullscreen: true

  android_12:
    image: assets/img/logo.jpg
    icon_background_color: "#334790"
    image_dark: assets/img/logo.jpg
    icon_background_color_dark: "#334790"

  web: false

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - assets/fonts/
    - assets/img/teams/
    - assets/languages/

  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
